Repository Open-Cascade-SAS/OCCT, pull requests merged in 2024-12, with the labels that each got.

#174 Configuration - Remove package precompiled definitions from CMake
  adm/cmake/occt_toolkit.cmake
Labels: 2. Enhancement, 1. Configuration

#175 Integration request to master
  adm/cmake/occt_toolkit.cmake
Labels: 2. IR

#179 Coding - Missing include in TopoDSToStep_Builder.hxx
  src/TopoDSToStep/TopoDSToStep_Builder.hxx
Labels: 2. Bug, 1. Coding

#181 0033664: Visualization - Selection does not work for simple shape
  src/StdSelect/StdSelect_BRepSelectionTool.cxx
  tests/v3d/bugs/bug33664_1
  tests/v3d/bugs/bug33664_2
Labels: 2. Bug, 1. Visualization

#182 Selection does not work for simple shape
  src/StdSelect/StdSelect_BRepSelectionTool.cxx
  tests/v3d/bugs/bug33664_1
  tests/v3d/bugs/bug33664_2
Labels: 2. Bug, 1. Visualization

#184 CR167: GLTF Import - Metadata support
  src/RWGltf/RWGltf_GltfJsonParser.cxx
  src/RWGltf/RWGltf_GltfJsonParser.hxx
  tests/metadata/gltf/A1
  tests/metadata/gltf/A2
  tests/metadata/gltf/A3
  tests/metadata/gltf/A4
  tests/metadata/gltf/A5
  tests/metadata/gltf/A6
  tests/metadata/gltf/A7
  tests/metadata/gltf/A8
  tests/metadata/gltf/A9
  tests/metadata/gltf/begin
  tests/metadata/gltf/end
  tests/metadata/gltf_export/A1
  tests/metadata/gltf_export/A2
  tests/metadata/gltf_export/A3
  tests/metadata/gltf_export/A5
  tests/metadata/gltf_export/A6
  tests/metadata/gltf_export/A7
  tests/metadata/gltf_export/A8
  tests/metadata/gltf_export/A9
  tests/metadata/gltf_export/end
  tests/metadata/grids.list
Labels: 2. Enhancement, 1. Data Exchange

#185 Documentation - Remove unnecessary fields from issue templates
  .github/ISSUE_TEMPLATE/Bug Report.yaml
  .github/ISSUE_TEMPLATE/Feature Request.yaml
Labels: 1. Documentation, 2. Enhancement

#186 Revert "0023638: Data Exchange - Reading IGES file produced invalid shape"
  src/IGESData/IGESData_IGESModel.cxx
  src/IGESData/IGESData_IGESModel.hxx
  src/IGESToBRep/IGESToBRep_Actor.cxx
  src/XSAlgo/XSAlgo_AlgoContainer.cxx
  src/XSAlgo/XSAlgo_AlgoContainer.hxx
  tests/bugs/iges/bug23638
Labels: 2. Bug, 1. Data Exchange, 2. Regression

#188 Coding - Clear up XSAlgo package
  src/XSAlgo/FILES
  src/XSAlgo/XSAlgo_AlgoContainer.cxx
  src/XSAlgo/XSAlgo_AlgoContainer.hxx
  src/XSAlgo/XSAlgo_AlgoContainer.lxx
  src/XSAlgo/XSAlgo_Caller.hxx
  src/XSAlgo/XSAlgo_ToolContainer.cxx
  src/XSAlgo/XSAlgo_ToolContainer.hxx
Labels: 2. Enhancement, 1. Coding

#192 Coding, GLTF - Isolate RapidJSon part
  src/RWGltf/RWGltf_GltfJsonParser.cxx
  src/RWGltf/RWGltf_GltfJsonParser.hxx
Labels: 1. Data Exchange, 1. Coding, 2. Regression

#193 Documentation - Issue Template update
  .github/ISSUE_TEMPLATE/Bug Report.yaml
  .github/ISSUE_TEMPLATE/Feature Request.yaml
Labels: 1. Documentation, 2. Enhancement

#197 Configuration - Debug Draco linking issue
  adm/cmake/3rdparty_macro.cmake
  adm/cmake/occt_macros.cmake
  adm/cmake/occt_toolkit.cmake
  src/DRAWEXE/CMakeLists.txt
  src/TKDEGLTF/CMakeLists.txt
  src/TKRWMesh/CMakeLists.txt
Labels: 1. Configuration, 2. Regression

#198 Configuration - Inspector with SymLink error
  CMakeLists.txt
  tools/CMakeLists.txt
Labels: 2. Bug, 1. Configuration

#189 Shape Healing interface update
  src/DE/DE_ShapeFixParameters.hxx
  src/ShapeProcess/ShapeProcess.cxx
  src/ShapeProcess/ShapeProcess.hxx
  src/XSAlgo/FILES
  src/XSAlgo/XSAlgo_AlgoContainer.cxx
  src/XSAlgo/XSAlgo_AlgoContainer.hxx
  src/XSAlgo/XSAlgo_ShapeProcessor.cxx
  src/XSAlgo/XSAlgo_ShapeProcessor.hxx
Labels: 2. Enhancement, 1. Data Exchange

#199 Documentation - Move `gendoc` to `adm` directory
  .github/workflows/build-docs.yml
  README.md
  adm/gendoc
  adm/gendoc.bat
  dox/build/build_documentation/building_documentation.md
  dox/contribution/documentation/documentation.md
Labels: 1. Documentation, 2. Enhancement

#200 Documentation - Add GH overview documentation build
  .github/workflows/build-docs.yml
Labels: 1. Documentation, 2. Enhancement

#205 Configuration - Add VCPKG Manifest mode support
  .github/workflows/build-occt-with-vcpkg.yml
  CMakeLists.txt
  adm/cmake/draco.cmake
  adm/cmake/ffmpeg.cmake
  adm/cmake/freeimage.cmake
  adm/cmake/freetype.cmake
  adm/cmake/jemalloc.cmake
  adm/cmake/occt_defs_flags.cmake
  adm/cmake/occt_macros.cmake
  adm/cmake/openvr.cmake
  adm/cmake/rapidjson.cmake
  adm/cmake/tbb.cmake
  adm/cmake/tcl.cmake
  adm/cmake/tk.cmake
  adm/cmake/vtk.cmake
  adm/vcpkg/ports/ffmpeg/0001-create-lib-libraries.patch
  adm/vcpkg/ports/ffmpeg/0003-fix-windowsinclude.patch
  adm/vcpkg/ports/ffmpeg/0004-fix-debug-build.patch
  adm/vcpkg/ports/ffmpeg/0006-fix-StaticFeatures.patch
  adm/vcpkg/ports/ffmpeg/0007-fix-lib-naming.patch
  adm/vcpkg/ports/ffmpeg/0009-Fix-fdk-detection.patch
  adm/vcpkg/ports/ffmpeg/0010-Fix-x264-detection.patch
  adm/vcpkg/ports/ffmpeg/0011-Fix-x265-detection.patch
  adm/vcpkg/ports/ffmpeg/0012-Fix-ssl-110-detection.patch
  adm/vcpkg/ports/ffmpeg/0013-define-WINVER.patch
  adm/vcpkg/ports/ffmpeg/0014-avfilter-dependency-fix.patch
  adm/vcpkg/ports/ffmpeg/0015-Fix-xml2-detection.patch
  adm/vcpkg/ports/ffmpeg/0017-Patch-for-ticket-9019-CUDA-Compile-Broken-Using-MSVC.patch
  adm/vcpkg/ports/ffmpeg/0018-libaom-Dont-use-aom_codec_av1_dx_algo.patch
  adm/vcpkg/ports/ffmpeg/0019-libx264-Do-not-explicitly-set-X264_API_IMPORTS.patch
  adm/vcpkg/ports/ffmpeg/0020-fix-aarch64-libswscale.patch
  adm/vcpkg/ports/ffmpeg/0022-fix-m1-hardware-decode-nal-bits.patch
  adm/vcpkg/ports/ffmpeg/0023-fix-qsv-init.patch
  adm/vcpkg/ports/ffmpeg/FindFFMPEG.cmake.in
  adm/vcpkg/ports/ffmpeg/build.sh.in
  adm/vcpkg/ports/ffmpeg/portfile.cmake
  adm/vcpkg/ports/ffmpeg/usage
  adm/vcpkg/ports/ffmpeg/vcpkg-cmake-wrapper.cmake
  adm/vcpkg/ports/ffmpeg/vcpkg.json
  adm/vcpkg/ports/jemalloc/fix-configure-ac.patch
  adm/vcpkg/ports/jemalloc/portfile.cmake
  adm/vcpkg/ports/jemalloc/preprocessor.patch
  adm/vcpkg/ports/jemalloc/vcpkg.json
  adm/vcpkg/ports/tcl/force-shell-install.patch
  adm/vcpkg/ports/tcl/portfile.cmake
  adm/vcpkg/ports/tcl/vcpkg.json
  adm/vcpkg/vcpkg-configuration.json
  adm/vcpkg/vcpkg.json
Labels: 2. Enhancement, 1. Configuration

#19 0033671: Coding - GeomTools performance update
  src/GeomTools/GeomTools.cxx
Labels: 2. Enhancement, 1. Coding, 3. Tests failed

#207 Coding - Fixing clang-tidy warnings
  src/Adaptor3d/Adaptor3d_CurveOnSurface.cxx
  src/AdvApp2Var/AdvApp2Var_ApproxF2var.cxx
  src/AdvApprox/AdvApprox_ApproxAFunction.cxx
  src/AppDef/AppDef_LinearCriteria.cxx
  src/AppDef/AppDef_Variational.cxx
  src/BSplCLib/BSplCLib.cxx
  src/BSplCLib/BSplCLib_BzSyntaxes.cxx
  src/BndLib/BndLib_Add2dCurve.cxx
  src/Convert/Convert_ConicToBSplineCurve.cxx
  src/Extrema/Extrema_ExtPElS.cxx
  src/Extrema/Extrema_GenExtPS.cxx
  src/FSD/FSD_BinaryFile.cxx
  src/FSD/FSD_CmpFile.cxx
  src/FSD/FSD_File.cxx
  src/Geom/Geom_BezierSurface.cxx
  src/Geom2dConvert/Geom2dConvert_ApproxArcsSegments.cxx
  src/GeomAdaptor/GeomAdaptor_Surface.cxx
  src/GeomLib/GeomLib.cxx
  src/IntAna2d/IntAna2d_AnaIntersection_2.cxx
  src/Message/Message_Msg.cxx
  src/Message/Message_PrinterOStream.cxx
  src/NCollection/NCollection_Array1.hxx
  src/OSD/OSD_File.cxx
  src/OSD/OSD_Path.cxx
  src/Resource/Resource_Unicode.cxx
  src/Standard/Standard_Dump.cxx
  src/Standard/Standard_Failure.cxx
  src/Standard/Standard_GUID.cxx
  src/Units/Units_UnitsDictionary.cxx
  src/gp/gp_Mat.cxx
  src/gp/gp_Mat2d.cxx
  src/math/math_BissecNewton.cxx
  src/math/math_Householder.cxx
  src/math/math_NewtonMinimum.cxx
  src/math/math_Recipes.cxx
Labels: 2. Enhancement, 1. Coding

#209 Coding - Fixing warning for Clang
  .github/workflows/build-and-test-multiplatform.yml
  adm/cmake/occt_defs_flags.cmake
  src/Aspect/Aspect_OpenVRSession.cxx
  src/ExpToCasExe/exptocas.tab.cxx
  src/IVtkDraw/IVtkDraw_Interactor.hxx
  src/IVtkTools/IVtkTools_DisplayModeFilter.hxx
  src/IVtkTools/IVtkTools_SubPolyDataFilter.hxx
  src/QABugs/QABugs_11.cxx
  src/ShapeProcess/ShapeProcess.cxx
  src/ShapeProcess/ShapeProcess.hxx
  src/StepFile/lex.step.cxx
  src/StepFile/step.tab.cxx
Labels: 2. Enhancement, 1. Coding

#210 Coding - Reorganize packages between TKExpress and TKMath
  src/TKExpress/PACKAGES
  src/TKMath/PACKAGES
  src/TKQADraw/EXTERNLIB
Labels: 2. Enhancement, 1. Coding

#211 Foundation Classes- Separate map's prime declaration
  src/NCollection/FILES
  src/NCollection/NCollection_BaseMap.cxx
  src/NCollection/NCollection_BaseMap.hxx
  src/NCollection/NCollection_BasePointerVector.cxx
  src/NCollection/NCollection_Primes.cxx
  src/NCollection/NCollection_Primes.hxx
  src/TColStd/TColStd_PackedMapOfInteger.cxx
  src/TCollection/FILES
  src/TCollection/TCollection.cxx
  src/TCollection/TCollection.hxx
Labels: 2. Enhancement, 1. Foundation Classes

#213 Foundation Classes - Move Map's algo part to external file
  src/BRepMesh/BRepMesh_FaceChecker.cxx
  src/BRepMesh/BRepMesh_ModelHealer.cxx
  src/BRepMesh/BRepMesh_NURBSRangeSplitter.cxx
  src/BRepOffset/BRepOffset_MakeOffset_1.cxx
  src/NCollection/FILES
  src/NCollection/NCollection_Map.hxx
  src/NCollection/NCollection_MapAlgo.hxx
  src/QABugs/QABugs_19.cxx
  src/QANCollection/QANCollection_Test.cxx
  src/ShapeUpgrade/ShapeUpgrade_UnifySameDomain.cxx
  src/XCAFDoc/XCAFDoc_Editor.cxx
Labels: 2. Enhancement, 1. Foundation Classes

#216 Testing - GH Mesa3D script update
  .github/workflows/build-and-test-multiplatform.yml
Labels: 2. Enhancement, 1. Testing

#217 Coding - Refactor Blend to remove gxx files
  src/BRepBlend/BRepBlend_CSWalking.cxx
  src/BRepBlend/BRepBlend_CSWalking.hxx
  src/BRepBlend/BRepBlend_CSWalking_0.cxx
  src/BRepBlend/BRepBlend_Walking.cxx
  src/BRepBlend/BRepBlend_Walking.hxx
  src/BRepBlend/BRepBlend_Walking_0.cxx
  src/BRepBlend/FILES
  src/Blend/Blend_CSWalking.gxx
  src/Blend/Blend_CSWalking.lxx
  src/Blend/Blend_CSWalking_1.gxx
  src/Blend/Blend_CSWalking_2.gxx
  src/Blend/Blend_CSWalking_3.gxx
  src/Blend/Blend_CSWalking_4.gxx
  src/Blend/Blend_Walking.gxx
  src/Blend/Blend_Walking.lxx
  src/Blend/Blend_Walking_1.gxx
  src/Blend/Blend_Walking_2.gxx
  src/Blend/Blend_Walking_3.gxx
  src/Blend/Blend_Walking_4.gxx
  src/Blend/FILES
Labels: 2. Enhancement, 1. Coding

#218 Coding - Coding - Refactor TopClass to remove gxx files
  src/BRepClass3d/BRepClass3d_SolidPassiveClassifier.cxx
  src/BRepClass3d/BRepClass3d_SolidPassiveClassifier.hxx
  src/BRepClass3d/BRepClass3d_SolidPassiveClassifier_0.cxx
  src/BRepClass3d/FILES
  src/TopClass/FILES
  src/TopClass/TopClass.cxx
  src/TopClass/TopClass_Classifier3d.gxx
  src/TopClass/TopClass_Classifier3d.lxx
  src/TopClass/TopClass_SolidClassifier.gxx
  src/TopClass/TopClass_SolidExplorer.cxx
  src/TopClass/TopClass_SolidExplorer.hxx
Labels: 2. Enhancement, 1. Coding

#219 Coding - Refactor IntCurveSurface to remove gxx files
  src/IntCurveSurface/FILES
  src/IntCurveSurface/IntCurveSurface_HCurveTool.gxx
  src/IntCurveSurface/IntCurveSurface_HCurveTool.lxx
  src/IntCurveSurface/IntCurveSurface_TheHCurveTool.cxx
  src/IntCurveSurface/IntCurveSurface_TheHCurveTool.hxx
  src/IntCurveSurface/IntCurveSurface_TheHCurveTool_0.cxx
Labels: 2. Enhancement, 1. Coding

#220 Coding - Remove unused source files and clean up header includes
  src/MeshVS/FILES
  src/MeshVS/MeshVS_MeshPrsBuilder.lxx
  src/MoniTool/FILES
  src/MoniTool/MoniTool_TimerSentry.cxx
  src/RWStepShape/FILES
  src/RWStepShape/RWStepShape_RWShapeDefinitionRepresentation_1.cxx
  src/TopOpeBRep/FILES
  src/TopOpeBRep/TopOpeBRep_DRAW.cxx
  src/TopoDS/FILES
  src/TopoDS/TopoDS_TCompSolid.hxx
  src/TopoDS/TopoDS_TCompSolid.lxx
  src/TopoDS/TopoDS_TCompound.hxx
  src/TopoDS/TopoDS_TCompound.lxx
  src/TopoDS/TopoDS_TEdge.hxx
  src/TopoDS/TopoDS_TEdge.lxx
  src/TopoDS/TopoDS_TFace.hxx
  src/TopoDS/TopoDS_TFace.lxx
  src/TopoDS/TopoDS_TShell.hxx
  src/TopoDS/TopoDS_TShell.lxx
  src/TopoDS/TopoDS_TSolid.hxx
  src/TopoDS/TopoDS_TSolid.lxx
  src/TopoDS/TopoDS_TVertex.hxx
  src/TopoDS/TopoDS_TVertex.lxx
  src/TopoDS/TopoDS_TWire.hxx
  src/TopoDS/TopoDS_TWire.lxx
  src/gce/FILES
  src/gce/gce_Root.cxx
Labels: 2. Enhancement, 1. Coding

#221 Coding - Refactor TopoDS.hxx
  src/TopoDS/FILES
  src/TopoDS/TopoDS.hxx
  src/TopoDS/TopoDS.lxx
Labels: 2. Enhancement, 1. Coding

#222 Coding - Combining multiple gxx IntWalk and IntPatch
  src/BRepFill/BRepFill_OffsetWire.cxx
  src/GCPnts/GCPnts_QuasiUniformDeflection.cxx
  src/IntPatch/FILES
  src/IntPatch/IntPatch_ImpImpIntersection.cxx
  src/IntPatch/IntPatch_ImpImpIntersection_0.gxx
  src/IntPatch/IntPatch_ImpImpIntersection_1.gxx
  src/IntPatch/IntPatch_ImpImpIntersection_2.gxx
  src/IntPatch/IntPatch_ImpImpIntersection_3.gxx
  src/IntPatch/IntPatch_ImpImpIntersection_4.gxx
  src/IntPatch/IntPatch_ImpImpIntersection_5.gxx
  src/IntPatch/IntPatch_ImpImpIntersection_6.gxx
  src/IntWalk/FILES
  src/IntWalk/IntWalk_IWalking.gxx
  src/IntWalk/IntWalk_IWalking_1.gxx
  src/IntWalk/IntWalk_IWalking_2.gxx
  src/IntWalk/IntWalk_IWalking_3.gxx
  src/IntWalk/IntWalk_IWalking_4.gxx
  src/IntWalk/IntWalk_IWalking_5.gxx
  src/IntWalk/IntWalk_IWalking_6.gxx
Labels: 2. Enhancement, 1. Coding

#224 Coding - Moving to use IsKind by type
  src/AIS/AIS_InteractiveContext.cxx
  src/MeshVS/MeshVS_Mesh.cxx
  src/MeshVS/MeshVS_Mesh.hxx
  src/XSDRAWIGES/XSDRAWIGES.cxx
  src/XSDRAWSTL/XSDRAWSTL.cxx
Labels: 2. Enhancement, 1. Coding
