Repository Open-Cascade-SAS/OCCT, pull requests merged in 2024-07, with the labels that each got.

#18 0033737: Data Exchange, XCAF - Implementing filter tree functionality
  src/XCAFDoc/XCAFDoc_Editor.cxx
  src/XCAFDoc/XCAFDoc_Editor.hxx
  src/XDEDRAW/XDEDRAW_Common.cxx
  tests/bugs/xde/bug33737
Labels: enhancement

#24 0033615: Modeling Algorithms - Partition algorithm creates unexpected vertices
  src/IntPatch/IntPatch_ALineToWLine.cxx
  tests/bugs/modalg_8/bug33615
  tests/bugs/modalg_8/bug33702
  tests/lowalgos/intss/bug29807_i1002
  tests/lowalgos/intss/bug29807_i5002
Labels: bug

#25 0033541: Modeling Algorithms - Simple sphere cut from cylinder fails
  src/IntPatch/IntPatch_WLineTool.cxx
  tests/bugs/modalg_8/bug33541
Labels: bug

#28 0033762: Documentation - Fix various typos found in codebase
  adm/templates/env.bat.in
  adm/templates/env.sh
  dox/specification/boolean_operations/boolean_operations.md
  dox/specification/pbr_math.md
  dox/user_guides/de_wrapper/de_wrapper.md
  dox/user_guides/draw_test_harness/draw_test_harness.md
  dox/user_guides/iges/iges.md
  dox/user_guides/modeling_algos/modeling_algos.md
  dox/user_guides/modeling_data/modeling_data.md
  samples/glfw/CMakeLists.txt
  samples/ocafsamples/TDataStd_Sample.cxx
  samples/ocafsamples/TPrsStd_Sample.cxx
  samples/qt/AndroidQt/ReadMe.md
  src/BOPTools/BOPTools_AlgoTools.cxx
  src/BRepFeat/BRepFeat_RibSlot.cxx
  src/BRepOffset/BRepOffset_MakeOffset.cxx
  src/ChFi2d/ChFi2d_FilletAlgo.cxx
  src/DrawResources/CheckCommands.tcl
  src/DsgPrs/DsgPrs_AnglePresentation.cxx
  src/DsgPrs/DsgPrs_AnglePresentation.hxx
  src/DsgPrs/DsgPrs_EqualRadiusPresentation.cxx
  src/IFSelect/IFSelect_GeneralModifier.hxx
  src/IFSelect/IFSelect_IntParam.hxx
  src/IFSelect/IFSelect_SignatureList.hxx
  src/IGESGeom/IGESGeom_CopiousData.cxx
  src/Image/Image_AlienPixMap.cxx
  src/Image/Image_Diff.hxx
  src/Interface/Interface_IntList.hxx
  src/NCollection/NCollection_CellFilter.hxx
  src/NCollection/NCollection_Mat4.hxx
  src/QABugs/QABugs_20.cxx
  src/ShapeFix/ShapeFix_ComposeShell.cxx
  src/ShapeFix/ShapeFix_ComposeShell.hxx
  src/ShapeFix/ShapeFix_Edge.cxx
  src/ShapeFix/ShapeFix_Shell.hxx
  src/ShapeFix/ShapeFix_Wire.cxx
  src/ShapeUpgrade/ShapeUpgrade_ShapeConvertToBezier.hxx
  src/ShapeUpgrade/ShapeUpgrade_ShapeDivide.hxx
  src/StepData/StepData_ReadWriteModule.hxx
  src/TCollection/TCollection.cxx
  src/TDocStd/TDocStd_Document.hxx
  src/TDocStd/TDocStd_XLinkTool.cxx
  src/TFunction/TFunction_Logbook.cxx
  src/Transfer/Transfer_ActorOfProcessForFinder.hxx
  src/Transfer/Transfer_ActorOfProcessForTransient.hxx
  src/Transfer/Transfer_TransientProcess.hxx
  src/XmlObjMgt/XmlObjMgt.cxx
  tests/bugs/fclasses/bug9848_1
  tests/bugs/fclasses/bug9848_2
  tests/bugs/modalg_5/bug24003
  tests/bugs/modalg_6/bug26313
  tests/bugs/step/bug233
  tests/bugs/step/pro19854
  tests/bugs/step/pro19895
  tests/lowalgos/intss/bug23699
  tests/lowalgos/intss/bug23732
  tests/perf/de/bug33046
  tests/perf/modalg/bug29093
Labels: documentation
