Repository Open-Cascade-SAS/OCCT, pull requests merged in 2024-09, with the labels that each got.

#55 0033805: Configuration - Implement GitHub Actions build scripts
  .github/workflows/codemsvc.yml
Labels: 2. Enhancement, 1. Coding, 3. Tests passed

#56 0033703: Data Exchange, Step Export - Transfer edge speed improvement
  src/TopoDSToStep/TopoDSToStep_MakeStepEdge.cxx
Labels: 2. Enhancement, 1. Data Exchange, 3. Tests passed

#73 Testing, GitHub - Marking warnings as errors
  .github/workflows/build-linux-gcc-x64-dynamic.yml
  .github/workflows/build-windows-msvc-x64-dynamic.yml
Labels: 2. Enhancement, 1. Testing

#20 0033723: Configuration - Removing Genproj and Update files
  adm/.gitignore
  adm/CMPLRS
  adm/genconf.tcl
  adm/genconfdeps.tcl
  adm/genproj.tcl
  adm/svgdiff.bat
  adm/templates/template.plist
  adm/templates/template.vc10
  adm/templates/template.vc10x
  adm/templates/template.vc7
  adm/templates/template.vc7x
  adm/templates/template.vc8
  adm/templates/template.vc8x
  adm/templates/template.vc9
  adm/templates/template.vc9x
  adm/templates/template.xcscheme
  adm/templates/template_dll.rc
  adm/templates/vcproj.user.vc9x
  adm/templates/vcxproj.user.vc10x
  adm/templates/xcode.sh
  adm/upgrade.dat
  adm/upgrade.tcl
  adm/upgrade_sample_orig.dat
  dox/build/build_occt/building_occt.md
  genconf
  genconf.bat
  genproj
  genproj.bat
  upgrade.bat
Labels: 2. Enhancement, 1. Configuration, 3. Tests passed

#78 0027410: Data Exchange, Iges Import - Possible resource leak when parsing an invalid file
  src/IGESFile/igesread.c
Labels: 2. Bug, 1. Data Exchange, 3. Tests passed

#81 Documentation - Update the main ReadMe
  README.md
  README.txt
Labels: 1. Documentation, 2. Enhancement

#84 Coding - GitIgnore update with .cache
  .gitignore
Labels: 2. Enhancement, 1. Coding

#82 0033498: Data Exchange, Step Export - Meshed pretessellated geometry is skipped on write
  src/RWStepVisual/RWStepVisual_RWComplexTriangulatedSurfaceSet.cxx
  src/STEPCAFControl/STEPCAFControl_GDTProperty.cxx
Labels: 2. Enhancement, 1. Data Exchange

#85 Coding - Reorganize code with constexpr
  src/Precision/Precision.hxx
  src/Standard/Standard_Character.hxx
  src/Standard/Standard_Integer.hxx
  src/Standard/Standard_Real.cxx
  src/Standard/Standard_Real.hxx
  src/Standard/Standard_ShortReal.hxx
Labels: 2. Enhancement, 1. Coding
