Repository Open-Cascade-SAS/OCCT, pull requests merged in 2025-05, with the labels that each got.

#513 Data Exchange, Step Export - Apply a scaling transformation
  src/DataExchange/TKDEIGES/DEIGES/DEIGES_Parameters.hxx
  src/DataExchange/TKDESTEP/DESTEP/DESTEP_ConfigurationNode.cxx
  src/DataExchange/TKDESTEP/DESTEP/DESTEP_Parameters.hxx
  src/DataExchange/TKDESTEP/GeomToStep/FILES.cmake
  src/DataExchange/TKDESTEP/GeomToStep/GeomToStep_MakeCartesianTransformationOperator.cxx
  src/DataExchange/TKDESTEP/GeomToStep/GeomToStep_MakeCartesianTransformationOperator.hxx
  src/DataExchange/TKDESTEP/STEPConstruct/STEPConstruct_Assembly.cxx
  src/DataExchange/TKDESTEP/STEPConstruct/STEPConstruct_Assembly.hxx
  src/DataExchange/TKDESTEP/STEPControl/STEPControl_ActorWrite.cxx
  src/DataExchange/TKDESTEP/STEPControl/STEPControl_ActorWrite.hxx
  src/DataExchange/TKDESTEP/StepToGeom/StepToGeom.cxx
  tests/bugs/step/bug_ocp1949
  tests/bugs/xde/bug27142
  tests/de_wrapper/configuration/A3
  tests/de_wrapper/configuration/A4
Labels: 2. Enhancement, 1. Data Exchange

#529 Modeling Algorithms - XCAFDoc_Editor::RescaleGeometry does not rescale translation of roots reference
  src/DataExchange/TKXCAF/XCAFDoc/XCAFDoc_AssemblyGraph.cxx
  tests/bugs/xde/ar10850
Labels: 2. Enhancement, 1. Application Framework, 1. Modeling

#530 Data Exchange - Add missed headers
  src/DataExchange/TKDEGLTF/RWGltf/RWGltf_CafReader.cxx
  src/DataExchange/TKDESTEP/GTests/StepTidy_BaseTestFixture.pxx
  src/DataExchange/TKDESTEP/GeomToStep/GeomToStep_MakeCartesianTransformationOperator.cxx
Labels: 2. Bug, 1. Data Exchange

#524 Testing - Target branch to compare validation of repo
  .github/actions/test-summary/action.yml
Labels: 2. Enhancement, 1. Testing

#523 Configuration - Fixed pathes to 3rd-party in cmake configuration
  adm/cmake/occt_macros.cmake
  adm/cmake/occt_toolkit.cmake
  src/DataExchange/TKDEIGES/CMakeLists.txt
  src/DataExchange/TKDEIGES/FILES.cmake
  src/DataExchange/TKDESTEP/CMakeLists.txt
  src/DataExchange/TKDESTEP/FILES.cmake
  src/DataExchange/TKXSBase/CMakeLists.txt
  src/DataExchange/TKXSBase/FILES.cmake
  src/FoundationClasses/TKMath/CMakeLists.txt
  src/FoundationClasses/TKMath/FILES.cmake
  src/FoundationClasses/TKernel/CMakeLists.txt
  src/FoundationClasses/TKernel/FILES.cmake
  src/ModelingAlgorithms/TKMesh/CMakeLists.txt
  src/ModelingAlgorithms/TKMesh/FILES.cmake
  src/ModelingData/TKBRep/CMakeLists.txt
  src/ModelingData/TKBRep/FILES.cmake
  src/Visualization/TKV3d/CMakeLists.txt
  src/Visualization/TKV3d/FILES.cmake
Labels: 2. Enhancement, 1. Configuration

#531 Testing - IR integration enable concurrency
  .github/workflows/build-and-test-multiplatform.yml
Labels: 2. Enhancement, 1. Testing

#528 Foundation Classes - Return value is overridden by OCCT
  src/Draw/TKDraw/Draw/Draw_BasicCommands.cxx
  src/Draw/TKQADraw/QABugs/QABugs_19.cxx
  src/Draw/TKQADraw/QANCollection/QANCollection_Perf.cxx
  src/FoundationClasses/TKernel/GTests/FILES.cmake
  src/FoundationClasses/TKernel/GTests/OSD_PerfMeter_Test.cxx
  src/FoundationClasses/TKernel/OSD/FILES.cmake
  src/FoundationClasses/TKernel/OSD/OSD_PerfMeter.cxx
  src/FoundationClasses/TKernel/OSD/OSD_PerfMeter.h
  src/FoundationClasses/TKernel/OSD/OSD_PerfMeter.hxx
  tests/bugs/fclasses/bug23237
Labels: 2. Bug, 1. Foundation Classes

#536 Testing - IR integration enable concurrency
  .github/workflows/build-and-test-multiplatform.yml
Labels: 1. Testing

#532 Modeling - BRepFilletAPI_MakeFillet Segfault with two curves and rim #501
  src/ModelingAlgorithms/TKFillet/ChFi3d/ChFi3d_Builder_2.cxx
  src/ModelingData/TKBRep/BRepAdaptor/BRepAdaptor_Surface.cxx
  tests/bugs/modalg_8/bug_gh501
Labels: 2. Bug, 1. Modeling

#514 Modeling - General Fuse (BOPAlgo_PaveFiller) optimization
  src/ModelingAlgorithms/TKBO/BOPAlgo/BOPAlgo_PaveFiller_6.cxx
  src/ModelingAlgorithms/TKBO/BOPDS/BOPDS_DS.cxx
  src/ModelingData/TKBRep/BRep/BRep_Tool.cxx
Labels: 2. Enhancement, 1. Modeling

#537 Configuration - Update minimum version of C++ to 17
  .github/actions/build-occt/action.yml
  CMakeLists.txt
  adm/cmake/occt_macros.cmake
  dox/build/build_occt/building_occt.md
Labels: 2. Enhancement, 1. Configuration

#518 Modeling - Bnd_BoundSortBox::Compare fails in some cases
  src/FoundationClasses/TKMath/Bnd/Bnd_BoundSortBox.cxx
  src/FoundationClasses/TKMath/Bnd/Bnd_BoundSortBox.hxx
  src/FoundationClasses/TKMath/GTests/Bnd_BoundSortBox_Test.cxx
  src/FoundationClasses/TKMath/GTests/FILES.cmake
Labels: 2. Bug, 1. Modeling

#542 Draw - Update DrawDefault script to handle missing directory cases
  resources/DrawResources/DrawDefault
Labels: 2. Bug, 1. DRAW

#540 Testing - Add a new compilation on Clang without PCH
  .github/actions/build-occt/action.yml
  .github/workflows/build-and-test-multiplatform.yml
  adm/cmake/occt_defs_flags.cmake
Labels: 2. Enhancement, 1. Testing

#543 Coding - Small optimization of StepData_StepReaderData
  src/DataExchange/TKDESTEP/StepData/StepData_StepReaderData.cxx
Labels: 2. Enhancement, 1. Coding

#549 Testing - GCC bug workaround for test NCollection_LocalArrayTest, CustomType
  src/FoundationClasses/TKernel/GTests/NCollection_LocalArray_Test.cxx
Labels: 2. Bug, 1. Testing

#557 Modeling - Infinite loop when Simplifying Fuse operation, CPU to 100%
  src/ModelingAlgorithms/TKShHealing/ShapeUpgrade/ShapeUpgrade_UnifySameDomain.cxx
  tests/bugs/modalg_8/bug_gh544
Labels: 2. Bug, 1. Modeling

#554 Data Exchange, GLTF - fix saving edges when Merge Faces is enabled
  src/DataExchange/TKDEGLTF/RWGltf/RWGltf_CafWriter.cxx
  src/DataExchange/TKDEGLTF/RWGltf/RWGltf_CafWriter.hxx
  src/DataExchange/TKDEGLTF/RWGltf/RWGltf_GltfJsonParser.cxx
  src/DataExchange/TKDEGLTF/RWGltf/RWGltf_TriangulationReader.cxx
Labels: 2. Bug, 1. Data Exchange

#561 Configuration - Fixed issue with CSF variable overwriting
  CMakeLists.txt
Labels: 2. Bug, 1. Configuration

#569 Coding - Refactor switch-case statements and improve memory management
  src/ApplicationFramework/TKCDF/LDOM/LDOMBasicString.cxx
  src/ApplicationFramework/TKCDF/LDOM/LDOM_BasicElement.cxx
  src/ApplicationFramework/TKCDF/PCDM/PCDM_ReadWriter.cxx
  src/FoundationClasses/TKernel/Standard/Standard_Macro.hxx
  src/FoundationClasses/TKernel/Standard/Standard_MemoryUtils.hxx
  src/FoundationClasses/TKernel/Units/Units_UnitsDictionary.cxx
  src/ModelingAlgorithms/TKGeomAlgo/IntCurve/IntCurve_IntConicConic_1.cxx
  src/ModelingAlgorithms/TKGeomAlgo/IntPatch/IntPatch_ImpPrmIntersection.cxx
  src/ModelingAlgorithms/TKGeomAlgo/TopTrans/TopTrans_CurveTransition.cxx
  src/ModelingAlgorithms/TKShHealing/ShapeConstruct/ShapeConstruct_ProjectCurveOnSurface.cxx
  src/ModelingData/TKG2d/Geom2dLProp/Geom2dLProp_NumericCurInf2d.cxx
  src/ModelingData/TKGeomBase/AdvApp2Var/AdvApp2Var_SysBase.cxx
  src/ModelingData/TKGeomBase/Extrema/Extrema_ExtCC2d.cxx
Labels: 2. Enhancement, 1. Coding

#562 Coding, Data Exchange - Optimize entity graph evaluating
  src/DataExchange/TKXSBase/Interface/Interface_Graph.cxx
Labels: 2. Enhancement, 1. Data Exchange, 1. Coding
