Repository Open-Cascade-SAS/OCCT, pull requests merged in 2025-02, with the labels that each got.

#322 Foundation Classes - BVH surface area calculation for transformed boxes
  src/BVH/BVH_Box.hxx
Labels: 1. Foundation Classes

#315 Data Exchange, Step Import - Adding product attributes to metadata
  src/DESTEP/DESTEP_ConfigurationNode.cxx
  src/DESTEP/DESTEP_Parameters.cxx
  src/DESTEP/DESTEP_Parameters.hxx
  src/DESTEP/DESTEP_Provider.cxx
  src/STEPCAFControl/STEPCAFControl_Reader.cxx
  src/STEPCAFControl/STEPCAFControl_Reader.hxx
  tests/de_wrapper/configuration/A3
  tests/de_wrapper/configuration/A4
  tests/metadata/gltf/A1
  tests/metadata/gltf/A2
  tests/metadata/gltf/A3
  tests/metadata/gltf/A4
  tests/metadata/gltf/A5
  tests/metadata/gltf/A6
  tests/metadata/gltf/A7
  tests/metadata/gltf/A8
  tests/metadata/gltf/A9
  tests/metadata/gltf/end
  tests/metadata/step/A1
  tests/metadata/step/A2
  tests/metadata/step/A3
  tests/metadata/step/A4
  tests/metadata/step/A5
  tests/metadata/step/A6
  tests/metadata/step/A7
  tests/metadata/step/A8
  tests/metadata/step/A9
  tests/metadata/step/end
Labels: 2. Enhancement, 1. Data Exchange

#323 Configuration - Git commit info missed
  adm/cmake/occt_macros.cmake
Labels: 1. Configuration

#325 Testing - GH Summary disabling for cancellation
  .github/workflows/build-and-test-multiplatform.yml
Labels: 1. Testing

#324 Data Exchange - StepExport non-manifold missed parameter
  src/DESTEP/DESTEP_ConfigurationNode.cxx
  tests/de_wrapper/configuration/A3
  tests/de_wrapper/configuration/A4
Labels: 1. Data Exchange

#326 Testing - Summary image diff keeping
  .github/actions/scripts/cleanup_test_images.py
  .github/workflows/build-and-test-multiplatform.yml
Labels: 1. Testing

#330 Testing - Disable summarization on cancellation
  .github/workflows/build-and-test-multiplatform.yml
Labels: 1. Testing

#329 Testing - Inspector building on GH
  .github/actions/build-tinspector/action.yml
  .github/actions/clang-format-check/action.yml
  .github/workflows/build-and-test-multiplatform.yml
  .github/workflows/clang-format-check.yml
  .gitignore
  adm/cmake/qt.cmake
  tools/TInspector/TInspector_Communicator.cxx
  tools/TInspector/TInspector_OpenFileDialog.cxx
  tools/TreeModel/TreeModel_Tools.cxx
Labels: 1. Testing

#243 GLTF Export - Edge and Vertex support
  src/RWGltf/RWGltf_CafWriter.cxx
  src/RWGltf/RWGltf_CafWriter.hxx
  src/RWMesh/FILES
  src/RWMesh/RWMesh_EdgeIterator.cxx
  src/RWMesh/RWMesh_EdgeIterator.hxx
  src/RWMesh/RWMesh_FaceIterator.cxx
  src/RWMesh/RWMesh_FaceIterator.hxx
  src/RWMesh/RWMesh_ShapeIterator.cxx
  src/RWMesh/RWMesh_ShapeIterator.hxx
  src/RWMesh/RWMesh_VertexIterator.cxx
  src/RWMesh/RWMesh_VertexIterator.hxx
  tests/de_mesh/gltf_write/draco_mesh
Labels: 2. Enhancement, 1. Data Exchange

#242 GLTF Import - Edge and Vertex support
  src/RWGltf/RWGltf_GltfJsonParser.cxx
  src/RWGltf/RWGltf_GltfLatePrimitiveArray.cxx
  src/RWGltf/RWGltf_GltfLatePrimitiveArray.hxx
  src/RWGltf/RWGltf_TriangulationReader.cxx
  src/RWGltf/RWGltf_TriangulationReader.hxx
  src/RWMesh/RWMesh_TriangulationReader.cxx
  src/RWMesh/RWMesh_TriangulationReader.hxx
  src/RWMesh/RWMesh_TriangulationSource.cxx
  src/RWMesh/RWMesh_TriangulationSource.hxx
  tests/de_mesh/gltf_write/empty
  tests/de_mesh/gltf_write/primitives
  tests/metadata/gltf/A2
  tests/metadata/gltf/A3
  tests/metadata/gltf/A4
  tests/metadata/gltf/A7
  tests/metadata/gltf/end
Labels: 2. Enhancement, 1. Data Exchange

#332 Testing - Marking failed code formatting
  .github/actions/clang-format-check/action.yml
  .github/workflows/build-and-test-multiplatform.yml
Labels: 1. Testing

#343 Data Exchange - Schema missed during export
  src/STEPControl/STEPControl_Controller.cxx
  src/STEPControl/STEPControl_Reader.cxx
  src/STEPControl/STEPControl_Writer.cxx
  src/STEPEdit/STEPEdit.cxx
Labels: 1. Data Exchange, 2. Regression

#342 Configuration - regression in wasm build
  src/OpenGl/OpenGl_GraphicDriver.cxx
Labels: 1. Build

#346 Coding - Refactor ShapeHealingMap to NCollection
  src/DE/DE_ShapeFixParameters.hxx
  src/IGESControl/IGESControl_Writer.cxx
  src/IGESControl/IGESControl_Writer.hxx
  src/IGESToBRep/IGESToBRep_Actor.cxx
  src/IGESToBRep/IGESToBRep_Reader.cxx
  src/IGESToBRep/IGESToBRep_Reader.hxx
  src/STEPCAFControl/STEPCAFControl_Reader.cxx
  src/STEPCAFControl/STEPCAFControl_Reader.hxx
  src/STEPCAFControl/STEPCAFControl_Writer.cxx
  src/STEPCAFControl/STEPCAFControl_Writer.hxx
  src/STEPControl/STEPControl_ActorRead.cxx
  src/STEPControl/STEPControl_ActorWrite.cxx
  src/STEPControl/STEPControl_Writer.cxx
  src/STEPControl/STEPControl_Writer.hxx
  src/ShapeProcess/ShapeProcess.cxx
  src/Transfer/Transfer_ActorOfFinderProcess.cxx
  src/Transfer/Transfer_ActorOfFinderProcess.hxx
  src/Transfer/Transfer_ActorOfTransientProcess.cxx
  src/Transfer/Transfer_ActorOfTransientProcess.hxx
  src/XSAlgo/XSAlgo_ShapeProcessor.cxx
  src/XSAlgo/XSAlgo_ShapeProcessor.hxx
  src/XSControl/XSControl_Reader.cxx
  src/XSControl/XSControl_Reader.hxx
  tests/de_wrapper/configuration/A3
  tests/de_wrapper/configuration/A4
Labels: 1. Data Exchange, 1. Coding

#340 Testing - Update GH Action for 7.9.0
  .github/actions/build-tinspector/action.yml
  .github/workflows/build-and-test-multiplatform.yml
  .github/workflows/build-multiconfig-msvc.yml
  src/Draw/Draw_Window.cxx
  tests/bugs/modalg_6/bug28054_2
Labels: 1. Testing

#331 Testing - Samples build on GH
  .github/actions/build-sample-csharp/action.yml
  .github/actions/build-sample-mfc/action.yml
  .github/actions/build-sample-qt/action.yml
  .github/actions/build-tinspector/action.yml
  .github/workflows/build-and-test-multiplatform.yml
  adm/templates/custom.build.sh.in
  adm/templates/env.build.sh.in
  adm/templates/env.install.sh.in
  samples/qt/FuncDemo/FuncDemo.pro
  samples/qt/IESample/IESample.pro
  samples/qt/OCCTOverview/OCCTOverview.pro
  samples/qt/Tutorial/Tutorial.pro
Labels: 1. Testing

#355 Data Exchange - STEP Export ignore write schema
  src/StepData/StepData_StepModel.cxx
  src/StepData/StepData_StepModel.hxx
Labels: 1. Data Exchange, 2. Regression

#357 Data Exchange - Step Import metadata crash protecting
  src/STEPCAFControl/STEPCAFControl_Reader.cxx
Labels: 1. Data Exchange

#365 Testing - Update GH testing to filter completed reference branch testing
  .github/workflows/build-and-test-multiplatform.yml
Labels: 1. Testing

#369 CMake - Disable building Overview by default
  CMakeLists.txt
Labels: 1. Configuration

#368 Data Exchange - IGES Import Degenerated BSpline crash
  src/IGESToBRep/IGESToBRep_BasicCurve.cxx
Labels: 1. Data Exchange

#256 Testing - WebAssembly build validation
  .github/workflows/build-multiconfig-mingw.yml
  .github/workflows/build-multiconfig-msvc.yml
  .github/workflows/build-multiconfig-ubuntu.yml
  .github/workflows/build-occt-wasm-ubuntu.yml
  .github/workflows/build-occt-with-vcpkg.yml
  CMakeLists.txt
Labels: 2. Enhancement, 1. Configuration, 1. Testing

#372 Modeling - SIGSEGV BRepAdaptor_Curve2d and UnifySameDomain
  src/BRepAdaptor/BRepAdaptor_Curve2d.cxx
  src/ShapeUpgrade/ShapeUpgrade_UnifySameDomain.cxx
Labels: 1. Modeling

#376 Testing - Remove installation of Visual C++ 2010
  .github/workflows/build-and-test-multiplatform.yml
Labels: 1. Testing

#377 Testing - Summarize only with success reference
  .github/workflows/build-and-test-multiplatform.yml
Labels: 1. Testing

#380 Coding - Bump version to 7.9.0 stable release
  adm/cmake/version.cmake
Labels: 1. Coding

#394 Coding - Bump version to 8.0.0.dev
  adm/cmake/version.cmake
Labels: 1. Coding

#392 Add flag for font mgr to avoid error message
  src/Font/Font_FontMgr.cxx
  src/Font/Font_FontMgr.hxx
Labels: 1. Visualization

#393 Data Exchange - DE Wrapper invalidating parameters after 'Load'
  dox/user_guides/de_wrapper/de_wrapper.md
  src/DEGLTF/DEGLTF_ConfigurationNode.cxx
  src/DEOBJ/DEOBJ_ConfigurationNode.cxx
  src/DEPLY/DEPLY_ConfigurationNode.cxx
  tests/de_wrapper/configuration/A5
Labels: 1. Data Exchange

#385 Refactor mouse click handling logic for improved double-click detection
  src/AIS/AIS_ViewController.cxx
Labels: 3. CLA approved
