Repository Open-Cascade-SAS/OCCT, pull requests merged in 2025-07, with the labels that each got.

#589 Documentation - Copilot instructions for OCCT development
  .github/copilot-instructions.md
  .gitignore
Labels: 1. Documentation

#595 Testing - Draw testing clear up
  tests/de/begin
  tests/de/iges_1/G8
  tests/de/iges_1/J9
  tests/de/step_1/E1
  tests/de/step_1/E2
  tests/de/step_1/G9
  tests/de/step_2/B3
  tests/de/step_2/Q5
  tests/de/step_2/Q6
  tests/de/step_3/B9
  tests/de/step_3/C8
  tests/de/step_3/E4
  tests/perf/heal/bug24596_1
  tests/perf/heal/bug24596_2
  tests/perf/modalg/bug32539_2
  tests/v3d/bugs/bug26139
Labels: 1. DRAW, 1. Testing

#594 Testing - GH Remove extra jobs
  .github/actions/test-summary/action.yml
  .github/workflows/build-and-test-multiplatform.yml
Labels: 1. Testing

#601 Data Exchange, Step Export - Preserving control directives
  src/DataExchange/TKDESTEP/GTests/FILES.cmake
  src/DataExchange/TKDESTEP/GTests/StepData_StepWriter_Test.cxx
  src/DataExchange/TKDESTEP/StepData/StepData_StepWriter.cxx
  src/DataExchange/TKDESTEP/StepData/StepData_StepWriter.hxx
Labels: 2. Bug, 1. Data Exchange

#609 Configuration - Fix link errors on macOS when not building using vcpkg
  CMakeLists.txt
Labels: 1. Configuration, 3. CLA approved

#612 Testing - Add performance summary posting to PR
  .github/actions/test-summary/action.yml
Labels: 2. Enhancement, 1. Testing

#611 Testing - Fix master validation workflow
  .github/actions/cmake-build-basic/action.yml
  .github/actions/cmake-build-full/action.yml
  .github/actions/setup-msys2/action.yml
  .github/actions/setup-ubuntu-deps/action.yml
  .github/actions/setup-windows-msvc-deps/action.yml
  .github/actions/vcpkg-setup/action.yml
  .github/workflows/build-multiconfig-mingw.yml
  .github/workflows/build-multiconfig-msvc.yml
  .github/workflows/build-multiconfig-ubuntu.yml
  .github/workflows/build-occt-wasm-ubuntu.yml
  .github/workflows/build-occt-with-vcpkg.yml
  .github/workflows/code-analysis.yml
  .github/workflows/daily-ir-vcpkg-configure.yml
  .github/workflows/master-validation.yml
  src/Visualization/TKService/Media/Media_CodecContext.cxx
  src/Visualization/TKService/Media/Media_FormatContext.cxx
Labels: 2. Bug, 2. Enhancement, 1. Testing

#616 Configuration - VCPKG add GTest feature
  .github/actions/run-gtest/action.yml
  CMakeLists.txt
  adm/vcpkg/vcpkg.json
Labels: 1. Configuration

#626 Configuration - Fix ARCH for older 32-bit macs
  adm/templates/env.install.sh.in
  adm/templates/env.sh
Labels: 2. Enhancement, 1. Configuration

#628 Testing - Fix skipped daily IR on macOS
  .github/workflows/daily-ir-vcpkg-configure.yml
Labels: 2. Bug, 1. Testing

#635 Foundation classes - Include brackets type fix
  src/DataExchange/TKDESTEP/StepFile/step.tab.hxx
  src/FoundationClasses/TKernel/NCollection/NCollection_DynamicArray.hxx
  src/FoundationClasses/TKernel/NCollection/NCollection_String.hxx
  src/FoundationClasses/TKernel/NCollection/NCollection_UtfIterator.hxx
  src/FoundationClasses/TKernel/NCollection/NCollection_UtfString.hxx
  src/FoundationClasses/TKernel/TCollection/TCollection_AsciiString.lxx
Labels: 2. Bug, 1. Foundation Classes

#637 Configuration - VCPKG extend feature list
  adm/vcpkg/vcpkg.json
Labels: 2. Enhancement, 1. Configuration

#647 Configuration, CMake - Build config file is invalid
  CMakeLists.txt
  adm/templates/custom.build.sh.in
Labels: 2. Bug, 1. Configuration

#649 Building - Remove GLTF files from XDEDRAW
  src/Draw/TKXDEDRAW/XDEDRAW/XDEDRAW.cxx
Labels: 1. Build

#650 Coding - Remove unused dependencies from TKXDEDRAW
  src/DataExchange/TKDESTEP/STEPCAFControl/STEPCAFControl_GDTProperty.cxx
  src/DataExchange/TKDESTEP/STEPCAFControl/STEPCAFControl_GDTProperty.hxx
  src/DataExchange/TKDESTEP/STEPCAFControl/STEPCAFControl_Writer.cxx
  src/DataExchange/TKXCAF/XCAFDimTolObjects/XCAFDimTolObjects_DimensionObject.cxx
  src/DataExchange/TKXCAF/XCAFDimTolObjects/XCAFDimTolObjects_DimensionObject.hxx
  src/Draw/TKXDEDRAW/EXTERNLIB.cmake
  src/Draw/TKXDEDRAW/XDEDRAW/XDEDRAW.cxx
  src/Draw/TKXDEDRAW/XDEDRAW/XDEDRAW_GDTs.cxx
  src/Draw/TKXSDRAWSTEP/XSDRAWSTEP/XSDRAWSTEP.cxx
Labels: 1. Coding

#655 Coding - Add .DS_Store to ignore list
  .gitignore
Labels: 1. Coding

#658 Testing - Create occt artefact action
  .github/actions/build-occt/action.yml
  .github/actions/build-sample-csharp/action.yml
  .github/actions/build-sample-mfc/action.yml
  .github/actions/build-sample-qt/action.yml
  .github/actions/build-tinspector/action.yml
  .github/actions/download-artifacts/action.yml
  .github/actions/retest-failures/action.yml
  .github/actions/run-gtest/action.yml
  .github/actions/run-tests/action.yml
  .github/actions/test-summary/action.yml
  .github/actions/upload-artifacts/action.yml
Labels: 1. Testing
