Repository Open-Cascade-SAS/OCCT, pull requests merged in 2025-01, with the labels that each got.

#233 DRAW - Static plugin factory refactor
  src/DRAWEXE/DRAWEXE.cxx
  src/DRAWEXE/EXTERNLIB_STATIC
Labels: 2. Bug, 1. DRAW

#234 Foundation Classes - Optimize IsKind operation
  src/Standard/Standard_Type.cxx
Labels: 2. Enhancement, 1. Foundation Classes

#235 Foundation Classes - Standard_Type Instance reorganization
  src/Standard/Standard_Transient.cxx
  src/Standard/Standard_Type.hxx
  src/TDataStd/TDataStd_Relation.cxx
Labels: 1. Foundation Classes

#236 Foundation Classes - Standard_Type avoiding C++ RTTI
  src/Standard/Standard_Type.cxx
  src/Standard/Standard_Type.hxx
Labels: 1. Foundation Classes

#238 Coding - Remove static global variables
  src/IGESAppli/IGESAppli_Protocol.cxx
  src/IGESBasic/IGESBasic_Protocol.cxx
  src/IGESDefs/IGESDefs_Protocol.cxx
  src/IGESDimen/IGESDimen_Protocol.cxx
  src/IGESDraw/IGESDraw_Protocol.cxx
  src/IGESGeom/IGESGeom_Protocol.cxx
  src/IGESGraph/IGESGraph_Protocol.cxx
  src/IGESSolid/IGESSolid_Protocol.cxx
Labels: 2. Enhancement, 1. Coding

#240 Coding - Deprecate Handle_* type usage
  dox/user_guides/draw_test_harness/draw_test_harness.md
  dox/user_guides/modeling_algos/modeling_algos.md
  src/BRepTest/BRepTest_BasicCommands.cxx
  src/PrsMgr/PrsMgr_Presentation3d.hxx
  src/PrsMgr/PrsMgr_PresentationManager3d.hxx
  src/QANCollection/QANCollection_Handle.cxx
  src/Standard/Standard_Handle.hxx
  src/Standard/Standard_Transient.hxx
  src/Standard/Standard_WarningsDisable.hxx
  src/TPrsStd/TPrsStd_AISPresentation.cxx
  src/V3d/V3d_Light.hxx
Labels: 2. Enhancement, 1. Coding

#248 Configuration - Library CSF directory separation
  adm/cmake/jemalloc.cmake
  adm/cmake/occt_macros.cmake
Labels: 2. Bug, 1. Configuration

#251 Testing - Ubuntu build validation
  .github/workflows/build-multiconfig-ubuntu.yml
  src/AdvApp2Var/AdvApp2Var_SysBase.cxx
Labels: 2. Enhancement, 1. Testing

#252 Testing - MSVC build validation
  .github/workflows/build-multiconfig-msvc.yml
Labels: 2. Enhancement, 1. Testing

#253 Testing - MinGW build validation
  .github/workflows/build-multiconfig-mingw.yml
  adm/cmake/3rdparty_macro.cmake
  adm/cmake/freetype.cmake
  adm/cmake/jemalloc.cmake
  adm/cmake/occt_defs_flags.cmake
Labels: 2. Enhancement, 1. Testing

#255 Foundation Classes - Standard_Type destructor static_assert
  src/Standard/Standard_Type.cxx
Labels: 1. Foundation Classes, 2. Regression

#246 Coding - Add clang-format configuration
  .clang-format
  CMakeLists.txt
  src/Approx/Approx_Array1OfAdHSurface.hxx
  src/Approx/Approx_Array1OfGTrsf2d.hxx
  src/Approx/Approx_Curve2d.cxx
  src/Approx/Approx_Curve2d.hxx
  src/Approx/Approx_Curve3d.cxx
  src/Approx/Approx_Curve3d.hxx
  src/Approx/Approx_CurveOnSurface.cxx
  src/Approx/Approx_CurveOnSurface.hxx
  src/Approx/Approx_CurvilinearParameter.cxx
  src/Approx/Approx_CurvilinearParameter.hxx
  src/Approx/Approx_CurvlinFunc.cxx
  src/Approx/Approx_CurvlinFunc.hxx
  src/Approx/Approx_FitAndDivide.hxx
  src/Approx/Approx_FitAndDivide2d.hxx
  src/Approx/Approx_FitAndDivide2d_0.cxx
  src/Approx/Approx_FitAndDivide_0.cxx
  src/Approx/Approx_HArray1OfAdHSurface.hxx
  src/Approx/Approx_HArray1OfGTrsf2d.hxx
  src/Approx/Approx_MCurvesToBSpCurve.cxx
  src/Approx/Approx_MCurvesToBSpCurve.hxx
  src/Approx/Approx_ParametrizationType.hxx
  src/Approx/Approx_SameParameter.cxx
  src/Approx/Approx_SameParameter.hxx
  src/Approx/Approx_SequenceOfHArray1OfReal.hxx
  src/Approx/Approx_Status.hxx
  src/Approx/Approx_SweepApproximation.cxx
  src/Approx/Approx_SweepApproximation.hxx
  src/Approx/Approx_SweepApproximation.lxx
  src/Approx/Approx_SweepFunction.cxx
  src/Approx/Approx_SweepFunction.hxx
  src/ApproxInt/ApproxInt_Approx.gxx
  src/ApproxInt/ApproxInt_ImpPrmSvSurfaces.gxx
  src/ApproxInt/ApproxInt_KnotTools.cxx
  src/ApproxInt/ApproxInt_KnotTools.hxx
  src/ApproxInt/ApproxInt_MultiLineTool.lxx
  src/ApproxInt/ApproxInt_SvSurfaces.cxx
  src/ApproxInt/ApproxInt_SvSurfaces.hxx
  src/DE/DE_ConfigurationContext.cxx
  src/DE/DE_ConfigurationContext.hxx
  src/DE/DE_ConfigurationNode.cxx
  src/DE/DE_ConfigurationNode.hxx
  src/DE/DE_Provider.cxx
  src/DE/DE_Provider.hxx
  src/DE/DE_ShapeFixConfigurationNode.cxx
  src/DE/DE_ShapeFixConfigurationNode.hxx
  src/DE/DE_Wrapper.cxx
  src/DE/DE_Wrapper.hxx
Labels: 2. Enhancement, 1. Coding

#262 Testing - Update dependencies to include additional font packages
  .github/workflows/build-and-test-multiplatform.yml
Labels: 2. Enhancement, 1. Testing

#263 Testing - Update file handling outside catch block
  tests/bugs/caf/bug27667
Labels: 2. Bug, 1. Testing

#264 Testing - Specify test result folder
  .github/workflows/build-and-test-multiplatform.yml
Labels: 2. Enhancement, 1. Testing

#265 Testing - Fix loading order of OCAF and XDE in bug tests
  tests/bugs/moddata_3/bug31136_4
  tests/bugs/moddata_3/bug31136_5
  tests/bugs/xde/begin
Labels: 2. Bug, 1. Testing

#266 Testing - Update path for propeller script in video recorder tests
  tests/v3d/anim/videorecorder
Labels: 2. Bug, 1. Testing

#267 Testing - Add cpulimit to address critical issue on Ubuntu
  tests/bugs/moddata_2/bug712_2
Labels: 2. Bug, 1. Testing

#272 Testing - Update retest artifact uploading
  .github/actions/testgrid/testlinuxclang.tcl
  .github/actions/testgrid/testlinuxgcc.tcl
  .github/workflows/build-and-test-multiplatform.yml
Labels: 2. Bug, 1. Testing

#281 Configuration - fix jemalloc installation
  adm/cmake/jemalloc.cmake
Labels: 1. Configuration, 3. CLA approved, 2. Regression

#279 Coding - Fix dracobuffer index out of bounds
  src/RWGltf/RWGltf_CafWriter.cxx
Labels: 2. Bug, 1. Data Exchange, 3. CLA approved

#247 Data Exchange - Update Readers with ShapeHealing parameters
  src/DE/DE_ShapeFixParameters.hxx
  src/DE/FILES
  src/DEIGES/DEIGES_ConfigurationNode.cxx
  src/DEIGES/DEIGES_ConfigurationNode.hxx
  src/DEIGES/DEIGES_Parameters.cxx
  src/DEIGES/DEIGES_Parameters.hxx
  src/DEIGES/DEIGES_Provider.cxx
  src/DEIGES/DEIGES_Provider.hxx
  src/DEIGES/FILES
  src/DESTEP/DESTEP_Parameters.cxx
  src/DESTEP/DESTEP_Parameters.hxx
  src/IGESCAFControl/IGESCAFControl_Reader.cxx
  src/IGESCAFControl/IGESCAFControl_Writer.cxx
  src/IGESCAFControl/IGESCAFControl_Writer.hxx
  src/IGESControl/IGESControl_ActorWrite.cxx
  src/IGESControl/IGESControl_ActorWrite.hxx
  src/IGESControl/IGESControl_Reader.cxx
  src/IGESControl/IGESControl_Reader.hxx
  src/IGESControl/IGESControl_Writer.cxx
  src/IGESControl/IGESControl_Writer.hxx
  src/IGESData/IGESData_GlobalSection.cxx
  src/IGESToBRep/IGESToBRep_Actor.cxx
  src/IGESToBRep/IGESToBRep_Actor.hxx
  src/IGESToBRep/IGESToBRep_Reader.cxx
  src/IGESToBRep/IGESToBRep_Reader.hxx
  src/STEPCAFControl/STEPCAFControl_Reader.cxx
  src/STEPCAFControl/STEPCAFControl_Reader.hxx
  src/STEPCAFControl/STEPCAFControl_Writer.cxx
  src/STEPCAFControl/STEPCAFControl_Writer.hxx
  src/STEPControl/STEPControl_ActorRead.cxx
  src/STEPControl/STEPControl_ActorRead.hxx
  src/STEPControl/STEPControl_ActorWrite.cxx
  src/STEPControl/STEPControl_ActorWrite.hxx
  src/STEPControl/STEPControl_Reader.cxx
  src/STEPControl/STEPControl_Reader.hxx
  src/STEPControl/STEPControl_Writer.cxx
  src/STEPControl/STEPControl_Writer.hxx
  src/ShapeProcess/ShapeProcess.cxx
  src/ShapeProcess/ShapeProcess.hxx
  src/StepToTopoDS/StepToTopoDS_TranslateEdgeLoop.cxx
  src/Transfer/Transfer_ActorOfFinderProcess.cxx
  src/Transfer/Transfer_ActorOfFinderProcess.hxx
  src/Transfer/Transfer_ActorOfTransientProcess.cxx
  src/Transfer/Transfer_ActorOfTransientProcess.hxx
  src/Transfer/Transfer_ProcessForTransient_0.cxx
  src/XDEDRAW/XDEDRAW_Shapes.cxx
  src/XSAlgo/XSAlgo_ShapeProcessor.cxx
  src/XSAlgo/XSAlgo_ShapeProcessor.hxx
  src/XSControl/XSControl_Reader.cxx
  src/XSControl/XSControl_Reader.hxx
  src/XSDRAWIGES/XSDRAWIGES.cxx
  src/XSDRAWSTEP/XSDRAWSTEP.cxx
  src/XSDRAWVRML/XSDRAWVRML.cxx
Labels: 2. Enhancement, 1. Data Exchange

#282 Data Exchange - DE Wrapper Shape Healing Parameters
  src/DE/DE_ShapeFixConfigurationNode.cxx
  src/DE/DE_ShapeFixConfigurationNode.hxx
  src/DE/FILES
  src/DEIGES/DEIGES_ConfigurationNode.cxx
  src/DEIGES/DEIGES_ConfigurationNode.hxx
  src/DEIGES/DEIGES_Parameters.cxx
  src/DEIGES/DEIGES_Parameters.hxx
  src/DEIGES/DEIGES_Provider.cxx
  src/DESTEP/DESTEP_ConfigurationNode.cxx
  src/DESTEP/DESTEP_ConfigurationNode.hxx
  src/DESTEP/DESTEP_Parameters.cxx
  src/DESTEP/DESTEP_Parameters.hxx
  src/DESTEP/DESTEP_Provider.cxx
  src/IGESControl/IGESControl_ActorWrite.cxx
  src/IGESControl/IGESControl_Reader.cxx
  src/IGESControl/IGESControl_Reader.hxx
  src/IGESControl/IGESControl_Writer.cxx
  src/IGESControl/IGESControl_Writer.hxx
  src/IGESToBRep/IGESToBRep_Actor.cxx
  src/IGESToBRep/IGESToBRep_Reader.cxx
  src/IGESToBRep/IGESToBRep_Reader.hxx
  src/STEPCAFControl/STEPCAFControl_Reader.cxx
  src/STEPCAFControl/STEPCAFControl_Reader.hxx
  src/STEPCAFControl/STEPCAFControl_Writer.cxx
  src/STEPCAFControl/STEPCAFControl_Writer.hxx
  src/STEPControl/STEPControl_ActorRead.cxx
  src/STEPControl/STEPControl_ActorWrite.cxx
  src/STEPControl/STEPControl_Reader.cxx
  src/STEPControl/STEPControl_Reader.hxx
  src/STEPControl/STEPControl_Writer.cxx
  src/STEPControl/STEPControl_Writer.hxx
  src/Transfer/Transfer_ActorOfFinderProcess.cxx
  src/Transfer/Transfer_ActorOfFinderProcess.hxx
  src/Transfer/Transfer_ActorOfTransientProcess.cxx
  src/Transfer/Transfer_ActorOfTransientProcess.hxx
  src/XSControl/XSControl_Reader.cxx
  src/XSControl/XSControl_Reader.hxx
  src/XSDRAWIGES/XSDRAWIGES.cxx
  src/XSDRAWSTEP/XSDRAWSTEP.cxx
  tests/de_wrapper/configuration/A3
  tests/de_wrapper/configuration/A4
Labels: 2. Enhancement, 1. Data Exchange

#283 Data Exchange - Clear up Step from Static_Interface
  src/APIHeaderSection/APIHeaderSection_MakeHeader.cxx
  src/DESTEP/DESTEP_ConfigurationNode.cxx
  src/DESTEP/DESTEP_Parameters.hxx
  src/HeaderSection/HeaderSection_Protocol.cxx
  src/HeaderSection/HeaderSection_Protocol.hxx
  src/RWStepAP214/RWStepAP214_ReadWriteModule.cxx
  src/STEPCAFControl/STEPCAFControl_Reader.cxx
  src/STEPCAFControl/STEPCAFControl_Writer.cxx
  src/STEPConstruct/STEPConstruct_ContextTool.cxx
  src/STEPConstruct/STEPConstruct_Part.cxx
  src/STEPConstruct/STEPConstruct_Styles.cxx
  src/STEPConstruct/STEPConstruct_UnitContext.cxx
  src/STEPConstruct/STEPConstruct_ValidationProps.cxx
  src/STEPControl/STEPControl_ActorRead.cxx
  src/STEPControl/STEPControl_ActorRead.hxx
  src/STEPControl/STEPControl_ActorWrite.cxx
  src/STEPControl/STEPControl_Reader.cxx
  src/StepAP214/StepAP214_Protocol.cxx
  src/StepAP214/StepAP214_Protocol.hxx
  src/StepData/StepData.cxx
  src/StepData/StepData_FileProtocol.cxx
  src/StepData/StepData_FileProtocol.hxx
  src/StepData/StepData_Protocol.cxx
  src/StepData/StepData_Protocol.hxx
  src/StepData/StepData_StepModel.cxx
  src/StepData/StepData_StepReaderData.cxx
  src/StepSelect/StepSelect_StepType.cxx
  src/StepToTopoDS/StepToTopoDS_Builder.cxx
  src/StepToTopoDS/StepToTopoDS_TranslateCompositeCurve.cxx
  src/StepToTopoDS/StepToTopoDS_TranslateEdgeLoop.cxx
  src/TopoDSToStep/TopoDSToStep_MakeBrepWithVoids.cxx
  src/TopoDSToStep/TopoDSToStep_MakeFacetedBrep.cxx
  src/TopoDSToStep/TopoDSToStep_MakeManifoldSolidBrep.cxx
  src/TopoDSToStep/TopoDSToStep_MakeShellBasedSurfaceModel.cxx
  src/TopoDSToStep/TopoDSToStep_MakeStepEdge.cxx
  src/TopoDSToStep/TopoDSToStep_MakeStepFace.cxx
  src/TopoDSToStep/TopoDSToStep_MakeStepVertex.cxx
  src/TopoDSToStep/TopoDSToStep_Tool.cxx
  tests/de_wrapper/configuration/A3
  tests/de_wrapper/configuration/A4
Labels: 2. Bug, 1. Data Exchange

#284 Data Exchange - Losing attributes on NonManifold STEP
  src/STEPControl/STEPControl_Controller.cxx
  src/ShapeUpgrade/ShapeUpgrade_RemoveLocations.hxx
  src/XSAlgo/XSAlgo_ShapeProcessor.cxx
  src/XSAlgo/XSAlgo_ShapeProcessor.hxx
  src/XSControl/XSControl_TransferWriter.cxx
  tests/bugs/step/bug33815
Labels: 2. Bug, 1. Data Exchange

#293 Documentation - Update links in README
  README.md
Labels: 1. Documentation

#307 Step thread safety improvement
  src/QABugs/QABugs_20.cxx
  src/StepFile/StepFile_Read.cxx
  src/XSControl/XSControl_WorkSession.cxx
  src/XSControl/XSControl_WorkSession.hxx
  tests/bugs/step/bug33657_1
  tests/bugs/step/bug33657_2
  tests/bugs/step/bug33657_3
  tests/bugs/step/bug33657_4
Labels: 2. Bug, 1. Data Exchange

#319 Configuration, TKV3d - remove redundant dependency from OpenGL
  src/TKV3d/EXTERNLIB
Labels: 1. Configuration
