Repository Open-Cascade-SAS/OCCT, pull requests merged in 2025-09, with the labels that each got.

#702 Testing - Resolving CICD issues
  .github/actions/configure-occt/action.yml
  src/FoundationClasses/TKMath/GTests/math_FunctionRoots_Test.cxx
Labels: 2. Bug, 1. Testing

#705 Testing - Add unit tests for PLib functionality
  src/FoundationClasses/TKMath/GTests/FILES.cmake
  src/FoundationClasses/TKMath/GTests/PLib_DoubleJacobiPolynomial_Test.cxx
  src/FoundationClasses/TKMath/GTests/PLib_HermitJacobi_Test.cxx
  src/FoundationClasses/TKMath/GTests/PLib_JacobiPolynomial_Test.cxx
  src/FoundationClasses/TKMath/GTests/PLib_Test.cxx
  src/FoundationClasses/TKMath/PLib/PLib_DoubleJacobiPolynomial.cxx
Labels: 2. Enhancement, 1. Testing

#706 Testing - Fix GTests for TKMath in Debug
  src/FoundationClasses/TKMath/GTests/math_BFGS_Test.cxx
  src/FoundationClasses/TKMath/GTests/math_FunctionRoot_Test.cxx
Labels: 2. Bug, 1. Testing

#731 Coding - Blame ignore for gxx formatting patch
  .git-blame-ignore-revs
Labels: 2. Enhancement, 1. Coding

#733 Data Exchange - Hang in STEPCAFControl_Reader
  src/ModelingAlgorithms/TKTopAlgo/BRepTopAdaptor/BRepTopAdaptor_FClass2d.cxx
Labels: 2. Bug, 1. Data Exchange
