Repository Open-Cascade-SAS/OCCT, pull requests merged in 2025-03, with the labels that each got.

#396 fixed: Degenerated curves were not handled by Arrange function. With …
  src/GeomFill/GeomFill_BSplineCurves.cxx
Labels: 1. Modeling, 3. CLA approved

#395 Configuration - Update VTK configuration and enable optional components
  adm/cmake/occt_csf.cmake
  adm/cmake/vtk.cmake
Labels: 1. Configuration

#399 Configuration - Update file globbing and condition checks for installation paths
  adm/cmake/occt_macros.cmake
  adm/cmake/occt_toolkit.cmake
  adm/templates/OpenCASCADEConfig.cmake.in
Labels: 1. Configuration

#400 Configuration - Extend CMake file filter regex
  adm/cmake/occt_macros.cmake
  adm/cmake/occt_toolkit.cmake
Labels: 1. Configuration

#407 Data Exchange - Datum Axis extraction issue
  src/STEPCAFControl/STEPCAFControl_Reader.cxx
Labels: 1. Data Exchange

#403 Configuration - Update VTK optional components
  adm/cmake/vtk.cmake
Labels: 1. Configuration

#410 Modeling - Improve handling of polygon parameters in NURBS conversion
  src/BRepTools/BRepTools_NurbsConvertModification.cxx
Labels: 1. Modeling

#418 Configuration - Remove BUILD_PATCH option in CMake
  CMakeLists.txt
  adm/cmake/occt_macros.cmake
  adm/cmake/occt_toolkit.cmake
  adm/cmake/vardescr.cmake
  adm/scripts/cmake_custom.bat.template
  adm/scripts/cmake_custom.sh.template
  adm/scripts/cmake_gen.bat
  adm/scripts/cmake_gen.sh
  tools/CMakeLists.txt
Labels: 2. Enhancement, 1. Configuration

#424 Configuration - Checking for FILES content
  adm/cmake/occt_macros.cmake
  src/DE/FILES
  src/ExpToCasExe/FILES
  src/TopClass/FILES
Labels: 1. Configuration

#419 Configuration - Enhance Qt5 directory detection for Windows
  adm/cmake/qt.cmake
Labels: 1. Configuration, 2. Regression

#432 Configuration - Remove -symbolic linker flag
  .github/workflows/build-occt-with-vcpkg.yml
  adm/cmake/occt_defs_flags.cmake
Labels: 1. Configuration

#427 Configuration - Adding resource packages to toolkit
  src/TKOpenGl/PACKAGES
  src/TKService/PACKAGES
  src/TKShHealing/PACKAGES
  src/TKXSBase/PACKAGES
Labels: 1. Configuration

#448 Data Exchange, Step - AP242 SchemaName remove dot
  src/StepAP214/StepAP214_Protocol.cxx
Labels: 2. Bug, 1. Data Exchange

#441 Documentation - Migration to CMake from TCL
  .github/actions/build-docs/action.yml
  CMakeLists.txt
  adm/UDLIST
  adm/cmake/occt_doc.cmake
  adm/cmake/vardescr.cmake
  adm/gendoc
  adm/gendoc.bat
  adm/gendoc.tcl
  adm/occaux.tcl
  adm/start.tcl
  dox/resources/occt_ug_html.doxyfile
  src/OS/ApplicationFramework.tcl
  src/OS/DataExchange.tcl
  src/OS/Draw.tcl
  src/OS/FILES
  src/OS/FoundationClasses.tcl
  src/OS/ModelingAlgorithms.tcl
  src/OS/ModelingData.tcl
  src/OS/Modules.tcl
  src/OS/TApplicationFramework.tcl
  src/OS/TModelingData.tcl
  src/OS/TTool.tcl
  src/OS/TVisualization.tcl
  src/OS/Tools.tcl
  src/OS/Visualization.tcl
Labels: 1. Documentation

#453 Configuration - Resource generation source path fix
  adm/cmake/occt_resources.cmake
Labels: 1. Configuration

#452 Documentation - Generation schema fixing
  CMakeLists.txt
  adm/cmake/occt_doc.cmake
Labels: 1. Documentation

#454 Configuration - Update resource path references in build scripts
  adm/templates/DRAWEXE.vcxproj.user.in
  adm/templates/custom.build.bat.in
  adm/templates/custom.build.sh.in
Labels: 1. Configuration

#457 Foundation Classes - Host resolving by itself
  src/FoundationClasses/TKernel/OSD/OSD_Host.cxx
Labels: 2. Bug, 1. Foundation Classes

#460 Documentation - Convert module and toolkit names to lowercase for URL generation
  adm/cmake/occt_doc.cmake
Labels: 1. Documentation

#458 Foundation Classes - Update signal handling for GLIBC compatibility on Linux
  src/FoundationClasses/TKernel/OSD/OSD_signal.cxx
Labels: 1. Foundation Classes

#459 Foundation Classes - Checking for MallInfo version
  src/FoundationClasses/TKernel/OSD/OSD_MemInfo.cxx
Labels: 1. Foundation Classes

#463 Testing - Remove PLib_JacobiPolynomial_Test.cxx from GTests
  src/FoundationClasses/TKMath/GTests/FILES.cmake
  src/FoundationClasses/TKMath/GTests/PLib_JacobiPolynomial_Test.cxx
Labels: 1. Testing

#467 Configuration - Re-Configuration time optimization
  adm/cmake/doxygen.cmake
  adm/cmake/eigen.cmake
  adm/cmake/ffmpeg.cmake
  adm/cmake/freetype.cmake
  adm/cmake/rapidjson.cmake
  adm/cmake/tcl.cmake
  adm/cmake/tk.cmake
  adm/cmake/vtk.cmake
Labels: 1. Configuration
